import{a as v,S as E,i as h}from"./assets/vendor-xklh1a1B.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const f of i.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function t(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(r){if(r.ep)return;r.ep=!0;const i=t(r);fetch(r.href,i)}})();const P="45097804-c04896a24774ae5ff52198fb8",$="https://pixabay.com/api/";async function b(e,o=1,t=20){try{const n=await v.get($,{params:{key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:t}});return{images:n.data.hits,total:n.data.totalHits}}catch(n){throw console.error("Fetching error:",n),n}}const L=document.getElementById("loader"),p=document.getElementById("image-gallery"),B=new E(".gallery-link",{captionsData:"alt",captionDelay:250});function I(e){if(!p)return;const o=e.map(t=>`
    <div class="gallery-item">
      <a href="${t.largeImageURL}" class="gallery-link">
        <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image"/>
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${t.likes}</p>
        <p class="info-item"><b>Views:</b> ${t.views}</p>
        <p class="info-item"><b>Comments:</b> ${t.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
      </div>
    </div>
  `).join("");p.insertAdjacentHTML("beforeend",o),B.refresh()}function c(e){h.error({title:"Error",message:e,position:"topRight"})}function w(e){L.style.display="block",e&&(e.style.display="none")}function d(e){L.style.display="none",e&&(e.style.display="block")}function u(){h.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}const O=document.getElementById("search-form"),R=document.getElementById("search-input"),y=document.getElementById("image-gallery"),s=document.getElementById("load-more");let a=1,g="",m=0;const l=15;O.addEventListener("submit",S);s.addEventListener("click",q);function S(e){e.preventDefault();const o=R.value.trim();if(o===""){c("Please enter a search term.");return}g=o,a=1,y.innerHTML="",w(s),b(g,a,l).then(({images:t,total:n})=>{d(s),m=n,t.length===0?(y.innerHTML="",c("Sorry, there are no images matching your search query. Please try again!"),s.style.display="none"):(I(t),t.length<l||t.length===m?(s.style.display="none",u()):s.style.display="block")}).catch(t=>{d(s),c("An error occurred while fetching images. Please try again later.")})}function q(){a+=1,w(s),b(g,a,l).then(({images:e})=>{I(e),d(s);const o=y.querySelector(".gallery-item");if(o){const{height:n}=o.getBoundingClientRect();window.scrollBy({top:n*2.5,behavior:"smooth"})}(a*l>=m||e.length<l)&&(s.style.display="none",u())}).catch(e=>{d(s),c("An error occurred while fetching images. Please try again later.")})}
//# sourceMappingURL=commonHelpers.js.map
